// ─────────────────────────────────────────────────────────────────────────
// Tool registry (Organ 0 ↔ organs contract).
//
// `toolRegistry` maps every ToolName to a ToolHandler. The orchestrator builds
// a ToolContext { sessionId, browser, runtime, repo, lessons, emit } and routes
// each LessonStep's tool call here. Handlers do the side effect (drive the
// shared browser, write an artifact, …) and `emit` the matching StageEvent so
// the classroom UI updates live.
//
// Server-only module: touches the filesystem + server adapters. Never import
// into a client component.
// ─────────────────────────────────────────────────────────────────────────

import { promises as fs } from "node:fs";
import path from "node:path";

import { buildPptOutline } from "@/integrations/browser";
import type {
  Box,
  ToolContext,
  ToolHandler,
  ToolName,
} from "@/types/contracts";

// ── arg coercion helpers (tool args are Record<string, unknown>) ────────────

function str(v: unknown, fallback = ""): string {
  return typeof v === "string" ? v : fallback;
}

function optStr(v: unknown): string | undefined {
  return typeof v === "string" ? v : undefined;
}

function strList(v: unknown): string[] | undefined {
  if (!Array.isArray(v)) return undefined;
  const out = v.filter((x): x is string => typeof x === "string");
  return out.length > 0 ? out : undefined;
}

function asBox(v: unknown): Box | undefined {
  if (v && typeof v === "object") {
    const b = v as Record<string, unknown>;
    if (
      typeof b.x === "number" &&
      typeof b.y === "number" &&
      typeof b.w === "number" &&
      typeof b.h === "number"
    ) {
      return { x: b.x, y: b.y, w: b.w, h: b.h };
    }
  }
  return undefined;
}

function asTarget(v: unknown): "chatgpt" | "generic" {
  return v === "generic" ? "generic" : "chatgpt";
}

function stripExt(name: string): string {
  return name.replace(/\.[a-z0-9]{1,8}$/i, "").trim();
}

/** Stable, filesystem-safe artifact filename: "<sessionId>-<sanitized-name>". */
function artifactFileName(sessionId: string, name: string): string {
  const safe =
    name.replace(/[^a-zA-Z0-9._-]+/g, "_").replace(/^_+|_+$/g, "") ||
    "artifact.txt";
  return `${sessionId}-${safe}`;
}

// Artifacts are written into Next's public/ dir so they're served at /artifacts/*.
const ARTIFACT_DIR = path.join(process.cwd(), "public", "artifacts");

// ── tool handlers ───────────────────────────────────────────────────────────

// Client/UI tools — pure StageEvent emitters that drive the teaching screen.

const showStep: ToolHandler = async (args, ctx) => {
  const index = typeof args.index === "number" ? args.index : 0;
  const title = str(args.title, "Step");
  const body = optStr(args.body) ?? optStr(args.say);
  ctx.emit({ type: "step", index, title, body });
  return { index, title };
};

const highlightArea: ToolHandler = async (args, ctx) => {
  const selector = optStr(args.selector);
  const label = optStr(args.label);
  const box = asBox(args.box);
  ctx.emit({ type: "highlight", selector, box, label });
  return { selector, box, label };
};

const writePrompt: ToolHandler = async (args, ctx) => {
  const text = str(args.text);
  const target = asTarget(args.target);
  ctx.emit({ type: "prompt", text, target });
  return { text, target };
};

const showOutput: ToolHandler = async (args, ctx) => {
  const text = str(args.text);
  const source = str(args.source, "output");
  ctx.emit({ type: "output", text, source });
  return { text, source };
};

const askCheckpoint: ToolHandler = async (args, ctx) => {
  const question = str(args.question, "Shall we continue?");
  const choices = strList(args.choices);
  ctx.emit({ type: "checkpoint", question, choices });
  return { question, choices };
};

const saveArtifact: ToolHandler = async (args, ctx) => {
  const kind = str(args.kind, "file");
  const name = str(args.name, `artifact-${Date.now()}.txt`);
  const fileName = artifactFileName(ctx.sessionId, name);
  const filePath = path.join(ARTIFACT_DIR, fileName);

  // Decide file content: explicit text wins; a pptx renders a slide outline;
  // anything else gets a small readable placeholder.
  let content: string;
  if (typeof args.text === "string" && args.text.length > 0) {
    content = args.text;
  } else if (kind === "pptx" || kind === "outline") {
    const topic = str(args.topic) || stripExt(name) || "Untitled";
    content = buildPptOutline(topic);
  } else {
    content = `${name}\n\nkind: ${kind}\nsession: ${ctx.sessionId}\n\n(Generated by ShareTeacher.)`;
  }

  await fs.mkdir(ARTIFACT_DIR, { recursive: true });
  await fs.writeFile(filePath, content, "utf8");

  const url = `/artifacts/${fileName}`;
  await ctx.repo.saveArtifact(ctx.sessionId, { kind, name, url });
  ctx.emit({ type: "artifact", kind, name, url });
  return { kind, name, url };
};

// Server/browser tools — drive the shared Kernel browser via the controller.

const startBrowserSession: ToolHandler = async (_args, ctx) => {
  // ShareTeacher binds EVERY browser session to the one persistent Kernel
  // profile (KERNEL_PROFILE_NAME) so the human's ChatGPT login is reused every
  // lesson. Any lesson-supplied profileId is intentionally ignored.
  //
  // Consume the PRE-WARMED browser kicked off at createSession when available
  // (so the ~12s Kernel cold start is already paid off the critical path); the
  // orchestrator's ensureBrowserLive also attaches the controller and starts the
  // always-on screenshot stream exactly once. Falls back to a cold start if no
  // warm session exists (older sessions / prewarm failure).
  const info = ctx.ensureBrowserLive
    ? await ctx.ensureBrowserLive()
    : await (async () => {
        const cold = await ctx.runtime.startSession(ctx.kernelProfile);
        await ctx.browser.attach(cold);
        return cold;
      })();
  // Persist phase + runtime id so stop()/summary can find the browser.
  try {
    await ctx.repo.updateSession(ctx.sessionId, {
      browserSessionId: info.sessionId,
      phase: "browser_live",
    });
  } catch {
    /* session row may not be updatable in degraded mode — non-fatal */
  }
  ctx.emit({ type: "browser_view", liveUrl: info.liveViewUrl });
  ctx.emit({ type: "status", phase: "browser_live" });
  return { sessionId: info.sessionId, liveViewUrl: info.liveViewUrl };
};

const browserOpen: ToolHandler = async (args, ctx) => {
  const url = str(args.url);
  if (!url) throw new Error("browser_open requires a 'url'");
  // Guardrail: the shared real browser may never wander off the current step's
  // allowlist (drives REAL chatgpt.com; off-allowlist navigation is blocked).
  if (!ctx.lessons.isAllowed(ctx.sessionId, url)) {
    throw new Error(`Blocked off-allowlist navigation to ${url}`);
  }
  await ctx.browser.open(url);
  // No synchronous screenshot here: the always-on stream shows the page filling
  // in within a frame, and a fast CDP navigate returns on commit (sub-second).
  return { url };
};

const browserObserve: ToolHandler = async (_args, ctx) => {
  const result = await ctx.browser.observe();
  ctx.emit({
    type: "output",
    text: result.text,
    source: result.title || result.url || "browser",
  });
  return result;
};

const browserClick: ToolHandler = async (args, ctx) => {
  const instruction =
    str(args.instruction) || str(args.target) || str(args.text) || "click";
  const index = typeof args.index === "number" ? args.index : undefined;
  await ctx.browser.click(instruction, index);
  // The always-on screenshot stream reflects the click result; no extra shot.
  return { clicked: instruction, index };
};

const browserType: ToolHandler = async (args, ctx) => {
  const text = str(args.text);
  const index = typeof args.index === "number" ? args.index : undefined;
  await ctx.browser.type(text, index);
  if (args.submit === true) {
    await ctx.browser.click("send");
  }
  // The always-on screenshot stream reflects the typed text / submit result.
  return { typed: text, index, submitted: args.submit === true };
};

const browserRunSkill: ToolHandler = async (args, ctx) => {
  const name = str(args.name);
  if (!name) throw new Error("browser_run_skill requires a 'name'");
  const skillArgs = (args.args as Record<string, unknown>) || {};
  await ctx.browser.runSkill(name, skillArgs);
  return { name, args: skillArgs };
};

const browserTask: ToolHandler = async (args, ctx) => {
  const goal = str(args.goal);
  const result = await ctx.browser.task(goal);
  ctx.emit({ type: "output", text: result.summary, source: "browser-task" });
  return result;
};

const browserScreenshot: ToolHandler = async (_args, ctx) => {
  const shot = await ctx.browser.screenshot();
  ctx.emit({ type: "screenshot", url: shot });
  return { url: shot };
};

const browserTakeoverUrl: ToolHandler = async (args, ctx) => {
  const url = await ctx.browser.takeoverUrl();
  const reason = str(args.reason, "human takeover requested");
  ctx.emit({ type: "takeover", url, reason });
  return { url, reason };
};

const browserStop: ToolHandler = async (_args, ctx) => {
  await ctx.browser.stop();
  return { stopped: true };
};

// ── registry ─────────────────────────────────────────────────────────────────

/** All 16 tools, keyed by ToolName. The orchestrator routes every call here. */
export const toolRegistry: Record<ToolName, ToolHandler> = {
  // client/UI
  show_step: showStep,
  highlight_area: highlightArea,
  write_prompt: writePrompt,
  show_output: showOutput,
  ask_checkpoint: askCheckpoint,
  save_artifact: saveArtifact,
  // server/browser
  start_browser_session: startBrowserSession,
  browser_open: browserOpen,
  browser_observe: browserObserve,
  browser_click: browserClick,
  browser_type: browserType,
  browser_task: browserTask,
  browser_screenshot: browserScreenshot,
  browser_takeover_url: browserTakeoverUrl,
  browser_stop: browserStop,
  browser_run_skill: browserRunSkill,
};

/** Every ToolName, derived from the registry so the two can never drift. */
export const ALL_TOOL_NAMES = Object.keys(toolRegistry) as ToolName[];

export type { ToolContext };
